CLUSTAL multiple sequence alignment by MUSCLE (3.8)


donkey              MFGIQENIPRGGTTMKEEPLGSGMNPV---------------------------RSWMHT
chicken             MFGIQESIQRSGSSMKEEPLGAGMNAV---------------------------RTWMQG
human_EBF1          MFGIQESIQRSGSSMKEEPLGSGMNAV---------------------------RTWMQG
dog                 MFGIQESIQRSGSSMKEEPLGSGMNAV---------------------------RTWMQG
A._californica      ------------------------------------------------------------
starfish            MFGIQDSLTRGTTNLKEEPTGTAQVGSI--------------------------RSWMQP
sea_cucumber        MFGIQDSLVRGTSNLKEEPITTSSASELPPHPVPVNGTTISTNGPVVAETPIIREPWMQP
                                                                                

donkey              AGVVDANTAAQSGVGLARAHFEKQPPSNLRKSNFFHFVLALYDRQGQPVEIERTAFVDFV
chicken             AGVLDASTAAQSGVGLARAHFEKQPPSNLRKSNFFHFVLALYDRQGQPVEIERTAFVGFV
human_EBF1          AGVLDANTAAQSGVGLARAHFEKQPPSNLRKSNFFHFVLALYDRQGQPVEIERTAFVGFV
dog                 AGVLDANTAAQSGVGLARAHFEKQPPSNLRKSNFFHFVLALYDRQGQPVEIERTAFVGFV
A._californica      ------------------------------------------------------------
starfish            SMVEQGSSSC----GLARAHFEKQPPSNLRKSNFFHFVIALYDRAGQPVEIERTQFIDFI
sea_cucumber        TMVDQGASSS----GLARAHFEKQPPSNLRKSNFFHFVIALYDRAGQPVEIERTAFVGFI
                                                                                

donkey              EKEKEPNNEKTNNGIHYKLQLLYSNGVRTEQDLYVRLIDSMTKQAIVYEGQDKNPEMCRV
chicken             EKEKEANSEKTNNGIHYRLQLLYSNGIRTEQDFYVRLIDSMTKQAIVYEGQDKNPEMCRV
human_EBF1          EKEKEANSEKTNNGIHYRLQLLYSNGIRTEQDFYVRLIDSMTKQAIVYEGQDKNPEMCRV
dog                 EKEKEANSEKTNNGIHYRLQLLYSNGIRTEQDFYVRLIDSMTKQAIVYEGQDKNPEMCRV
A._californica      ------------------------------------------------------------
starfish            EKEREPDSAKTNNGIHYRLQLLYNNGARTEQDLYVRLIDSMTKQAITYEGQDKNPEMCRV
sea_cucumber        EKDTEPTTQKTNNGIHYRVILLYHNGEYVHQKPIYICIWLLYSKAIIYEGQDKNPEMCRV
                                                                                

donkey              LLTHEIMCSRCCDKKSCGNRNETPSDPVIIDRFFLKFFLKCNQNCLKNAGNPRDMRRFQV
chicken             LLTHEIMCSRCCDKKSCGNRNETPSDPVIIDRFFLKFFLKCNQNCLKNAGNPRDMRRFQV
human_EBF1          LLTHEIMCSRCCDKKSCGNRNETPSDPVIIDRFFLKFFLKCNQNCLKNAGNPRDMRRFQV
dog                 LLTHEIMCSRCCDKKSCGNRNETPSDPVIIDRFFLKFFLKCNQNCLKNAGNPRDMRRFQV
A._californica      -------------------------------------------------GNPRDMRRFQV
starfish            LLTHEIMCSRCCDKKSCGNRNETPSDPVIIDRFFLKFFLKCNQNCLKNAGNPRDMRRFQV
sea_cucumber        LLTHEVMCSRCCDKKSCGNRNETPSDPVIIDRFFLKFFLKCNQNCLKNAGNPRDMRRFQV
                                                                     ***********

donkey              VVSTTVNVDGHVLAVSDNMFVHNNSKHGRRARRLDPSEGTAPSYLEN-ATPCIKAISPSE
chicken             VVSTTVNVDGHVLAVSDNMFVHNNSKHGRRARRLDPSEGT-PSYLEHAATPCIKAISPSE
human_EBF1          VVSTTVNVDGHVLAVSDNMFVHNNSKHGRRARRLDPSEGT-PSYLEHAATPCIKAISPSE
dog                 VVSTTVNVDGHVLAVSDNMFVHNNSKHGRRARRLDPSEGT-PSYLEHAATPCIKAISPSE
A._californica      AISTSTAVDGPLLAVSDNMFVHNNSKHGRRARRLDPTEG---------ATPCIKAICPSE
starfish            VISTTPNVDGHVLAVSDNMFVHNNSKHGRRARRLDPSEG---------ATPCIKAISPSE
sea_cucumber        VVSTTPNVDGHVLAMSDNMFVHNNSKHGRRARRLDPSEG---------ATPCIKAISPSE
                    .:**:  *** :**:*********************:**         ********.***

donkey              GWTTGGATVIIIGDNFFDGLQVVFGTMLVWSELITPHAIRVQTPPRHIPGVVEVTLSYKS
chicken             GWTTGGATVIIIGDNFFDGLQVIFGTMLVWSELITPHAIRVQTPPRHIPGVVEVTLSYKS
human_EBF1          GWTTGGATVIIIGDNFFDGLQVIFGTMLVWSELITPHAIRVQTPPRHIPGVVEVTLSYKS
dog                 GWTTGGATVIIIGDNFFDGLQVIFGTMLVWSELITPHAIRVQTPPRHIPGVVEVTLSYKS
A._californica      GWATGGTTVILIGDNFFDGLQVVFGTMLVWSELITSHAIRVQTPPRHIPGVVEVTLSYKS
starfish            GWTTGGSTVIIVGENFFDGLQVVFGTMIVWSELITAHAIRVQTPPRHIPGVVEVTLSYKS
sea_cucumber        GWTTGGATVIIVGDNFFDGLQVVFGSMIVWSELITSHAIRVQTPPRHIPGVVEVTLSYKS
                    **:***:***::*:********:**:*:*******.************************

donkey              KQFCKGAPGRFVYTALNEPTIDYGFQRLQKVIPRHPGDPERLPKEVLLKRAADLVEALYG
chicken             KQFCKGTPGRFIYTALNEPTIDYGFQRLQKVIPRHPGDPERLPKEVILKRAADLVEALYG
human_EBF1          KQFCKGTPGRFIYTALNEPTIDYGFQRLQKVIPRHPGDPERLPKEVILKRAADLVEALYG
dog                 KQFCKGTPGRFIYTALNEPTIDYGFQRLQKVIPRHPGDPERLPKEVILKRAADLVEALYG
A._californica      KQFCKGAPGRFVYTALTEPTIDYGFQRLMKLVPRHPGDPERLPKEIILKRAADLAEALYS
starfish            KQFCKGAPGRFVYVSLTEPTIDYGFQRLSKLVPRHPGDGDRLPKEIILKRAADLAEVLYG
sea_cucumber        KQFCKGAPGRFVYVSLTEPTIDYGFQRLSKLVPRHPGDPERLPKEIILKRAADLAEALYS
                    ******:****:*.:*.*********** *::****** :*****::*******.*.**.

donkey              MPHNNQEIILKRAADIAEALYSVPRNHNQIPTLGNTPAHTGMMGVNSFSSQLAVNVSETS
chicken             MPHNNQEIILKRAADIAEALYSVPRNHNQLPALANTSVHAGMMGVNSFSGQLAVNVSEAS
human_EBF1          MPHNNQEIILKRAADIAEALYSVPRNHNQLPALANTSVHAGMMGVNSFSGQLAVNVSEAS
dog                 MPHNNQEIILKRAADIAEALYSVPRNHSQLPALTNTSVHAGMMGVNSFSGQLAVNVSEAS
A._californica      MPRNPNQLSLPT-----------PRS----PAMNNPA----MSGFNAYPSQLAVSVSDTA
starfish            MPRN--QVPIPA-----------PRS----PAINNSSGSSGLVPMNSFSSQLSLGEHEAS
sea_cucumber        MPRN--QLPIAP-----------PRS----PALNNSPGSGSLVPMNSFGSQLSVHGDHDG
                    **.*  :: :             **.    *:: *..    :  .*:: .**::     .

donkey              QAND--QVGYSRN--TSSVSPRGYVPS-STPQQSNYNTV--STS--MNGYGSGA-MANLG
chicken             QATS--Q-GFTRN--SSSVSPHGYVPS-TTPQQTNYNSV--TTS--MNGYGNAG-MSNLG
human_EBF1          QATN--Q-GFTRN--SSSVSPHGYVPS-TTPQQTNYNSV--TTS--MNGYGSAA-MSNLG
dog                 QATN--Q-GFTRN--SSSVSPHGYVPS-TTPQQTNYNSV--STS--MNGYGTAA-MSNLG
A._californica      VNGQWEEAGYNRSH-SSSVSPRGY------------------------------------
starfish            GSEQ--QSGFSRVQPSSALSPRGYSSGISTPHSSNGSTGSYSS---MNGYASASNLSNMA
sea_cucumber        SSEQ--QSGFSRVQPGSTLSPRGYTTG-LSSHSSSGSPTSYSSSSALNGYGPG--MTNVG
                       .  : *:.*    *::**.**                                    

donkey              VPGSPGFLNGSSANSPYGIVPS----SPTMAASSVTLPSNCSSTHGIFSFSPANVISAVK
chicken             --GSPTFLNGSAANSPYAIVPS----SPTM-ASSTSLPSNCSSSSGIFSFSPANMVSAVK
human_EBF1          --GSPTFLNGSAANSPYAIVPS----SPTM-ASSTSLPSNCSSSSGIFSFSPANMVSAVK
dog                 --GSPTFLNGSAANSPYAIVPS----SPTM-ASSTSLPSNCSSSSGIFSFSPANMVSAVK
A._californica      ------------------------------------------------------------
starfish            IPSSPSLFNGTATAAPSSSPPSLPHPPPSSNGTGGSSHRTASASPGIFSFSPANMITAVK
sea_cucumber        VPSSPSIFNGATSK----------------------------------------------
                                                                                

donkey              QKSAFAPVVRPQASPPPSCTSANG-----NGLQAMSGLVVPPM-----------------
chicken             QKSAFAPVVRPQTSPPPTCTSTNG-----NSLQAISGMIVPPM-----------------
human_EBF1          QKSAFAPVVRPQTSPPPTCTSTNG-----NSLQAISGMIVPPM-----------------
dog                 QKSAFAPVVRPQTSPPPTCTSTNG-----NSLQAISGMIVPPM-----------------
A._californica      ------------------------------------------------------------
starfish            QKSAFAPVVRCGPSSPSPGSGPAGMIGPVAGASGSTTMMSPSFCGVGGPFALPTCGAHTY
sea_cucumber        ------------------------------------------------------------
                                                                                

donkey              ---------
chicken             ---------
human_EBF1          ---------
dog                 ---------
A._californica      ---------
starfish            GTHIESPSK
sea_cucumber        ---------
                             
